libraries:
  Anime:
    - in_history:
        range: day
        collection:
          name: This day in history
          sync_mode: sync
    - in_history:
        range: week
        collection:
          name: This week in history
          sync_mode: sync
    - in_history:
        range: month
        collection:
          name: This month is history
          sync_mode: sync
  Series:
    - in_history:
        range: day
        collection:
          name: This day in history
    - extended_status:
        returning_soon:
          enabled: True
          mode: all
          collection_dir: collections/
          overlay_dir: overlays/
          days_ahead: 90
          collection:
            name: Returning Soon
            sync_mode: sync
          overlay:
            text: "RETURNING {{MM}}/{{DD}}"
            text_color: "#FFFFFF"
            background_color: "#00000066"
        airing_next:
          enabled: True
          mode: overlay
          collection:
            name: Currently Airing
        new_airing_next:
          enabled: True
          mode: collection
          collection:          
            name: Newly Airing
  Movies:
    - by_size:
        limit: 24
        order: desc
        min: 5GB
        max: 25GB
        collection:
          sync_mode: append
          sort_title: "!1234"
settings:
  kometa_config: config.yml
  data_source: tmdb
