libraries:
  Anime:
    - in_history:
        range: day
        collection_name: This day in history
        collection:
          sync_mode: sync
    - in_history:
        range: week
        collection_name: This week in history
        collection:
          sync_mode: sync
    - in_history:
        range: month
        collection_name: This month in history
        collection:
          sync_mode: sync
  Series:
    - in_history:
        range: day
        collection_name: This day in history
    - extended_status:
        returning_soon:
          enabled: True
          mode: all
          collection_title: Returning Soon
          collection_save_dir: collections/
          overlay_save_dir: overlays/
          days_ahead: 90
          collection:
            name: Returning Soon
            sync_mode: sync
          overlay:
            text: RETURNING {{MM/DD}}
            text_color: "#FFFFFF"
            background_color: "#00000066"
        airing_next:
          enabled: True
          mode: overlay
          collection_title: Currently Airing
        new_airing_next:
          enabled: True
          mode: collection
          collection_title: Newly Airing
  Movies:
    - by_size:
        limit: 24
        order: desc
        min: 5GB
        max: 25GB
        collection:
          sync_mode: append
          sort_title: "!1234"
settings:
  kometa_config: config.yml
  data_source: tmdb
