libraries:
  Anime:
    - extended_status:
        returning_soon:
          enabled: true
          days_ahead: 180
    - in_history:
        enabled: true
        range: day
        collection:
          name: This day in history
          sync_mode: sync
    - in_history:
        enabled: true
        range: week
        collection:
          name: This week in history
          sync_mode: sync
    - in_history:
        enabled: true
        range: month
        collection:
          name: This month is history
          sync_mode: sync
  Series:
    - in_history:
        range: day
        collection:
          name: This day in history
    - extended_status:
        returning_soon:
          enabled: True
          mode: all
          collection_dir: collections/
          overlay_dir: overlays/
          days_ahead: 90
          collection:
            name: Returning Soon
            sync_mode: sync
          overlay:
            status_text: "RETURNING {{M}} / {{DD}}"
            status_font_color: "#FFFFFE"
        airing_next:
          enabled: True
          mode: overlay
          collection:
            name: Currently Airing
        airing:
          enabled: True
        new:
          enabled: True
          mode: all
          collection:          
            name: New Series
        new_airing_next:
          enabled: True
          mode: all
          collection:
            name: New - Airing
          overlay:
            status_text: 'New - Airing {{MM}} / {{DD}}'
  Movies:
    - by_size:
        limit: 24
        order: desc
        min: 5GB
        max: 25GB
        collection:
          sync_mode: append
          sort_title: "!1234"
settings:
  kometa_config: config.yml
  data_source: tmdb
