libraries:
  Anime:                         # Plex Libraries to read from. Can enter multiple libraries.
  - by_size: 
      direction: desc
      collection:
        visible_home: true
  - by_size:
      minimum: 1
      maximum: 10
      trakt_list_privacy: public
      direction: desc
      collection_title: Order my pickles
      collection:
        visible_home: False
        sort_title: "!2234"
  - in-history:
      range: month
  - in-history:
  Series:
  - returning-soon:
      refresh: 30
      days_ahead: 90
      collection:
        sync_mode: sync
      overlay:
        back_color: "#65437899"
        horizontal_align: center
        back_align: left
  - by_size:
      direction: desc
  - in-history:
      range: month
      collection_title: My Series In History by month
  - missing_episodes:
      style: dot
  Movies:
  - by_size:
      minimum: 5
