name: develop workflow
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'main.py'
      - 'Dockerfile'
      - 'pattrmm.py'
      - 'vars.py'
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/insertdisc/pattrmm:develop .

      - name: Push Docker image
        run: docker push ghcr.io/insertdisc/pattrmm:develop
