on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'Dockerfile'
      - 'pattrmm.py'
      - 'vars.py'
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t pattrmm:latest .

      - name: Push Docker image
        run: docker push pattrmm:latest
